# Generated by Django 5.0.5 on 2024-05-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_blog_owner_alter_searchhistory_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_registration',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
